# Generated by Django 5.0 on 2023-12-16 10:34

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rvc_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('url', models.CharField(max_length=50, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('images', models.ImageField(blank=True, upload_to='photos/Brands')),
                ('availiable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'RevenueCenter',
                'verbose_name_plural': 'Revenue Center',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RVC_Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_Number', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/categories')),
                ('revenue_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVC.revenuecenter')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RVC.status')),
            ],
            options={
                'verbose_name': 'RVC_Seats',
                'verbose_name_plural': 'RVC Seats',
            },
        ),
    ]
