# Generated by Django 5.1.4 on 2026-05-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='gift_as',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='source_item',
        ),
    ]
