# Generated by Django 5.1.4 on 2026-05-10 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cartitem_gift_as_remove_cartitem_source_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='gift_as',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_items', to='carts.cartitem'),
        ),
    ]
