# Generated by Django 5.1.4 on 2026-05-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_gift_as_cartitem_source_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='gift_as',
            new_name='is_gift',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='source_item',
            new_name='parent_item',
        ),
    ]
