# Generated by Django 5.0 on 2024-01-04 17:59

import ckeditor.fields
import django.db.models.deletion
import django_quill.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_name', models.CharField(max_length=50, unique=True)),
                ('Brand_name_ka', models.CharField(max_length=50, null=True, unique=True)),
                ('Brand_name_en', models.CharField(max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('url', models.CharField(max_length=50, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_ka', ckeditor.fields.RichTextField(null=True)),
                ('description_en', ckeditor.fields.RichTextField(null=True)),
                ('images', models.ImageField(upload_to='photos/Brands')),
                ('availiable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_name_ka', models.CharField(max_length=50, null=True, unique=True)),
                ('category_name_en', models.CharField(max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('description_ka', models.TextField(blank=True, max_length=500, null=True)),
                ('description_en', models.TextField(blank=True, max_length=500, null=True)),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/categories')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner_name', models.CharField(max_length=50, unique=True)),
                ('Banner_name_ka', models.CharField(max_length=50, null=True, unique=True)),
                ('Banner_name_en', models.CharField(max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', django_quill.fields.QuillField(max_length=25550000)),
                ('description_ka', django_quill.fields.QuillField(max_length=25550000, null=True)),
                ('description_en', django_quill.fields.QuillField(max_length=25550000, null=True)),
                ('images', models.ImageField(upload_to='photos/Banners')),
                ('availiable', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50, unique=True, verbose_name='Product name')),
                ('Product_name_ka', models.CharField(max_length=50, null=True, unique=True, verbose_name='Product name')),
                ('Product_name_en', models.CharField(max_length=50, null=True, unique=True, verbose_name='Product name')),
                ('slug', models.SlugField(unique=True)),
                ('test', ckeditor.fields.RichTextField()),
                ('test_ka', ckeditor.fields.RichTextField(null=True)),
                ('test_en', ckeditor.fields.RichTextField(null=True)),
                ('SKU', models.CharField(max_length=50)),
                ('Serial_numb', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('discount_price', models.FloatField(default=0)),
                ('images', models.ImageField(upload_to='photos/Products')),
                ('datasheet', models.FileField(blank=True, upload_to='photos/Datasheets')),
                ('stock', models.IntegerField(default=50)),
                ('is_availiable', models.BooleanField(default=True)),
                ('is_new', models.BooleanField(default=True)),
                ('is_on_sale', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
                ('related', models.ManyToManyField(blank=True, to='shop.product')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/products')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'productgallery',
                'verbose_name_plural': 'product gallery',
            },
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=50, unique=True)),
                ('subcategory_name_ka', models.CharField(max_length=50, null=True, unique=True)),
                ('subcategory_name_en', models.CharField(max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('maincategory_name', models.CharField(max_length=50)),
                ('is_availiable', models.BooleanField(default=True)),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory'),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100)),
                ('variation_value', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
