# Generated by Django 5.0 on 2024-01-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_remove_category_the_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['my_order'], 'verbose_name': 'subcategory', 'verbose_name_plural': 'subcategories'},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
