# Generated by Django 5.0.8 on 2024-08-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_options_product_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['my_order'], 'verbose_name': 'subcategory_name', 'verbose_name_plural': 'subcategories'},
        ),
    ]
