# Generated by Django 5.1.4 on 2024-12-28 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_subcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('color_code', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': '4. Colors',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': '5. Sizes',
            },
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name_plural': 'Variations'},
        ),
        migrations.RemoveField(
            model_name='variation',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_category',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_value',
        ),
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ImageField(null=True, upload_to='product_imgs/'),
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='variation',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
        ),
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.size'),
        ),
    ]
