# Generated by Django 5.1.4 on 2025-01-31 11:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='test',
            field=ckeditor.fields.RichTextField(verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='test_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='test_ka',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Full Description'),
        ),
    ]
