# Generated by Django 5.1.4 on 2025-01-31 11:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_short_alter_product_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_ka',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Short Description'),
        ),
    ]
