# Generated by Django 5.1.4 on 2025-03-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_short_en_product_short_ka'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='title_ka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
