# Generated by Django 5.1.4 on 2025-04-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_color_title_en_color_title_ka'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='discount_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
