# Generated by Django 5.1.4 on 2025-04-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_variation_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='discount_price',
            field=models.FloatField(default=0),
        ),
    ]
