# Generated by Django 5.1.4 on 2025-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_variation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='hamburger_menu',
            field=models.BooleanField(default=True),
        ),
    ]
