# Generated by Django 5.1.4 on 2025-05-07 15:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_banner_hamburger_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Full Description'),
        ),
    ]
