# Generated by Django 5.1.4 on 2025-05-07 16:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Full Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='material_ka',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Full Description'),
        ),
    ]
