# Generated by Django 5.1.4 on 2025-06-23 08:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_ka',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='page_name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='page_name_ka',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
