# Generated by Django 5.1.4 on 2025-11-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_page_description_en_page_description_ka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Meta_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Meta name'),
        ),
    ]
