# Generated by Django 5.1.4 on 2025-11-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Meta_title_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Meta name'),
        ),
        migrations.AddField(
            model_name='product',
            name='Meta_title_ka',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Meta name'),
        ),
    ]
