# Generated by Django 5.1.4 on 2025-11-21 15:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='description_ka',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='name_ka',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabric',
            name='title_ka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
