# Generated by Django 5.1.4 on 2025-11-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_about_us_description_en_about_us_description_ka_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabric',
            options={'verbose_name_plural': '6. ქსოვილი'},
        ),
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.fabric'),
        ),
    ]
