# Generated by Django 5.1.4 on 2025-11-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_fabric_options_product_fabric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fabric',
        ),
    ]
