# Generated by Django 5.1.4 on 2025-11-25 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_product_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.fabric'),
        ),
    ]
