# Generated by Django 5.1.4 on 2026-01-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_variation_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Meta_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='text_block',
            field=models.TextField(blank=True, max_length=10500),
        ),
    ]
