# Generated by Django 5.1.4 on 2026-01-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_category_meta_title_category_text_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Meta_title_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Meta_title_ka',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_block_en',
            field=models.TextField(blank=True, max_length=10500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='text_block_ka',
            field=models.TextField(blank=True, max_length=10500, null=True),
        ),
    ]
