# Generated by Django 5.1.4 on 2026-03-12 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_category_meta_title_en_category_meta_title_ka_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_UsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/aboutus')),
                ('title', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.about_us')),
            ],
            options={
                'verbose_name': 'aboutusgallery',
                'verbose_name_plural': 'about us gallery',
            },
        ),
    ]
