# Generated by Django 5.1.4 on 2026-03-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_about_usgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_usgallery',
            options={'verbose_name': 'aboutusgallery', 'verbose_name_plural': 'about gallery'},
        ),
        migrations.AddField(
            model_name='about_us',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
