# Generated by Django 5.1.4 on 2026-03-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_about_usgallery_options_about_us_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about_us',
            name='title_ka',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
