# Generated by Django 5.1.4 on 2026-04-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_about_us_title_en_about_us_title_ka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('MainButton', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(upload_to='photos/SiteContent')),
                ('PriceList', models.FileField(blank=True, upload_to='photos/SiteContent')),
                ('register', models.CharField(blank=True, max_length=200, unique=True)),
                ('lang', models.CharField(blank=True, max_length=200)),
                ('stock', models.CharField(blank=True, max_length=200)),
                ('Address', models.CharField(blank=True, max_length=200)),
                ('VAT', models.CharField(blank=True, max_length=200)),
                ('Language', models.CharField(blank=True, max_length=200)),
                ('Cart', models.CharField(blank=True, max_length=200)),
                ('callus', models.CharField(blank=True, max_length=200)),
                ('fb_link', models.CharField(blank=True, max_length=200)),
                ('insta_link', models.CharField(blank=True, max_length=200)),
                ('youtube_link', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('contact_us', models.CharField(blank=True, max_length=200)),
                ('addresstext', models.CharField(blank=True, max_length=200)),
                ('socialtext', models.CharField(blank=True, max_length=200)),
                ('emailtext', models.CharField(blank=True, max_length=200)),
                ('tools', models.CharField(blank=True, max_length=200)),
                ('user', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email_address', models.CharField(blank=True, max_length=200)),
                ('user_phone', models.CharField(blank=True, max_length=200)),
                ('profile', models.CharField(blank=True, max_length=200)),
                ('save_changes', models.CharField(blank=True, max_length=200)),
                ('my_orders', models.CharField(blank=True, max_length=200)),
                ('edit_profile', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
