# Generated by Django 5.1.4 on 2026-04-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_site_content_address_en_site_content_address_ka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_content',
            name='colors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='site_content',
            name='colors_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site_content',
            name='colors_ka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site_content',
            name='filters',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='site_content',
            name='filters_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site_content',
            name='filters_ka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site_content',
            name='sizes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='site_content',
            name='sizes_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site_content',
            name='sizes_ka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
