# Generated by Django 5.1.4 on 2026-04-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_site_content_colors_site_content_colors_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_content',
            name='price',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='site_content',
            name='price_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site_content',
            name='price_ka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site_content',
            name='reset_filters',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='site_content',
            name='reset_filters_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site_content',
            name='reset_filters_ka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
