# Generated by Django 5.1.4 on 2026-04-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_site_content_price_site_content_price_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_content',
            name='search',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='site_content',
            name='search_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site_content',
            name='search_ka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
