# Generated by Django 5.1.4 on 2026-04-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_site_content_search_site_content_search_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_content',
            name='pages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='site_content',
            name='pages_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site_content',
            name='pages_ka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
