# Generated by Django 5.1.4 on 2026-05-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_site_content_pages_site_content_pages_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
    ]
