# Generated by Codex on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_category_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_content',
            name='sale_countdown_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site_content',
            name='sale_countdown_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
