# Generated by Codex on 2026-08-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_site_content_sale_countdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCountdown',
            fields=[],
            options={
                'verbose_name': 'Sale Countdown',
                'verbose_name_plural': 'Sale Countdown',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.site_content',),
        ),
    ]