# Generated by Codex on 2026-08-26

from datetime import datetime

from django.db import migrations
from django.utils import timezone


def set_default_sale_countdown_end(apps, schema_editor):
    SiteContent = apps.get_model('shop', 'Site_Content')
    ends_at = timezone.make_aware(
        datetime(2026, 8, 31, 23, 59, 59),
        timezone.get_current_timezone(),
    )
    SiteContent.objects.filter(
        name='DEFAULT',
        sale_countdown_ends_at__isnull=True,
    ).update(sale_countdown_ends_at=ends_at)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_salecountdown_proxy'),
    ]

    operations = [
        migrations.RunPython(set_default_sale_countdown_end, migrations.RunPython.noop),
    ]