"""
Django settings for solutioner project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-development-only-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Keep local development on the requested host instead of redirecting to the
# production domain. Production overrides this list in settings_prod.py.
CANONICAL_HOST_EXEMPT = ('localhost', '127.0.0.1', 'testserver')


PAYGE_PASSWORD = os.environ.get("PAYGE_PASSWORD", "")
PAYGE_MERCHANT_ID = os.environ.get("PAYGE_MERCHANT_ID", "")
TBC_CLIENT_ID = os.environ.get("TBC_CLIENT_ID", "")
TBC_CLIENT_SECRET = os.environ.get("TBC_CLIENT_SECRET", "")
TBC_ACCESS_TOKEN_API_KEY = os.environ.get("TBC_ACCESS_TOKEN_API_KEY", "")
TBC_PAYMENTS_API_KEY = os.environ.get("TBC_PAYMENTS_API_KEY", "")
BOG_CLIENT_ID = os.environ.get("BOG_CLIENT_ID", "")
BOG_CLIENT_SECRET = os.environ.get("BOG_CLIENT_SECRET", "")
FLITT_PAYMENT_KEY = os.environ.get("FLITT_PAYMENT_KEY", "")
FLITT_MERCHANT_ID = os.environ.get("FLITT_MERCHANT_ID", "")

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',

] 

# Application definition

INSTALLED_APPS = [
    # 'django_ledger',
    'taggit',
    'jazzmin',
    'modeltranslation',
    'Project',
    'shop',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'django.contrib.sites',
    # 'django.contrib.redirects',
    'django.contrib.staticfiles',
    'django_quill',
    'ckeditor',
    'carts',
    'accounts',
    'formtools',
    'orders',
    'RVC',
    'admin_reorder',
    'adminsortable2',
    'django_cleanup.apps.CleanupConfig',
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    'import_export',
    "allauth.socialaccount.providers.google",
]





MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'language.DefaultLanguageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    # 'django.middleware.common.BrokenLinkEmailsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.ForceCanonicalDomainAndLanguageMiddleware',
    # 'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
    'allauth.account.middleware.AccountMiddleware',
    
]


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': os.environ.get("GOOGLE_CLIENT_ID", ""),
            'secret': os.environ.get("GOOGLE_CLIENT_SECRET", ""),
            'key': ''
        }
    }
}
ROOT_URLCONF = 'solutioner.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.Product_all',
                'shop.context_processors.menu_links_tv',
                'shop.context_processors.menu_links',
                'shop.context_processors.page_all',
                'shop.context_processors.About_Usall',
                'shop.context_processors.menu_links_catts',
                'shop.context_processors.get_filters',
                'carts.context_processors.counter',
                # 'carts.context_processors.carttest',
                # 'carts.context_processors.carttest2',
                # 'carts.context_processors.carttest_shipping',
                'carts.context_processors.wishlist',
                'shop.context_processors.defaultcontent',
            ],
        },
    },
]

WSGI_APPLICATION = 'solutioner.wsgi.application'

TAGGIT_CASE_INSENSITIVE = True


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


OMNISEND_API_KEY = os.environ.get("OMNISEND_API_KEY", "")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
#
AUTH_USER_MODEL = 'accounts.Account'
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ka'

TIME_ZONE = 'Asia/Tbilisi'

USE_I18N = True

USE_TZ = True

USE_L10N = True

LANGUAGES = [
    ('en', 'English'),
    ('ka', 'Georgian'),
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
LOCALE_PATHS = (os.path.join(BASE_DIR, 'locale'),)
DEFAULT_LANGUAGE = 'ka'
MODELTRANSLATION_LANGUAGES = ('ka', 'en')
TRANSLATABLE_MODEL_MODULES = ['shop.Product','shop.Category','shop.Banner','shop.subcategory','shop.Brand']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = [
    'solutioner/static',
]
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR /'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR /'media'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
LOCALE_PATHS = (os.path.join(BASE_DIR, 'locale'),)
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

X_FRAME_OPTIONS = 'SAMEORIGIN'

JAZZMIN_SETTINGS = {
    "site_title": "OldSupra.ge",

    "site_header": "OldSupra.ge",


    "navigation_expanded": True,

    "related_modal_active": True,

    "show_ui_builder": True,

}


from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.INFO: "",
    50: "critical",
}


INSTALLED_APPS += ["anymail"]

EMAIL_BACKEND = "anymail.backends.mailjet.EmailBackend"
ANYMAIL = {
    "MAILJET_API_KEY": os.environ.get("MAILJET_API_KEY", ""),
    "MAILJET_SECRET_KEY": os.environ.get("MAILJET_SECRET_KEY", ""),
}
DEFAULT_FROM_EMAIL = 'contact@oldsupra.ge'





# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST      = "in-v3.mailjet.com"
# EMAIL_PORT      = 465
# EMAIL_USE_TLS   = True
# EMAIL_HOST_USER = os.environ.get("MAILJET_SMTP_USER", "")
# EMAIL_HOST_PASSWORD = os.environ.get("MAILJET_SMTP_PASSWORD", "")
# DEFAULT_FROM_EMAIL = 'contact@oldsupra.ge'

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms',
             'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
                       'HiddenField']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',

            ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        'height': 291,
        'width': '100%',
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 940,
        'toolbarCanCollapse': True,
        'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}
SITE_ID = 1

SOCIALACCOUNT_PROVIDERS = {

    "google": {
        "SCOPE": [
            "profile",
            "email"
            ],
            "AUTH_PARAMS" : {"access_type": "online"}

        }
}


ADMIN_REORDER = (
    # Keep original label and models
    'sites',

    # Rename app
    {'app': 'auth', 'label': 'Authorisation'},

    # Reorder app models
    {'app': 'shop', 'models': ('shop.User', 'auth.Group')},

    # Exclude models
    {'app': 'auth', 'models': ('auth.User', )},

    # Cross-linked models
    {'app': 'auth', 'models': ('auth.User', 'sites.Site')},

    # models with custom name
    {'app': 'auth', 'models': (
        'auth.Group',
        {'model': 'auth.User', 'label': 'Staff'},
    )},
)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'flitt_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'flitt_callback.log',
        },
        'liberty_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'liberty_callback.log',
        },
        'bog_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'bog_callback.log',
        },
    },
    'loggers': {
        'flitt_payments': {
            'handlers': ['flitt_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'bog_callback': {
            'handlers': ['bog_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'liberty_payments': {
            'handlers': ['liberty_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


ADMINS = [
    ('oldsupra', 'contact@oldsupra.ge'),
    ('andro', 'andro.besalashvili@gmail.com'),
    ('irina', 'irinejaparidze03@gmail.com')
]



SOCIALACCOUNT_ADAPTER = 'accounts.adapter.CustomSocialAccountAdapter'
ACCOUNT_AUTHENTICATED_SIGNUP = True
ACCOUNT_EMAIL_VERIFICATION = 'none'  # This skips email verification.
ACCOUNT_EMAIL_REQUIRED = True


LOGIN_REDIRECT_URL = "/accounts/dashboard"
LOGOUT_REDIRECT_URL = "/"

CELERY_BROKER_URL = 'redis://localhost:6379/0'
