# Generated by Django 5.1.4 on 2025-04-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, choices=[('bog', 'Bank Of Georgia'), ('tbc', 'TBC Bank')], max_length=10, null=True),
        ),
    ]
