# Generated by Django 5.1.4 on 2025-06-20 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment_bank'),
        ('shop', '0019_product_material_en_product_material_ka'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.variation'),
        ),
    ]
