# Generated by Django 5.1.4 on 2026-01-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderproduct_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, choices=[('bog', 'Bank Of Georgia'), ('tbc', 'TBC Bank'), ('flitt', 'Flitt'), ('liberty', 'Liberty Bank')], max_length=10, null=True),
        ),
    ]
