# Generated by Django 5.1.4 on 2026-01-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_checkout_data_alter_payment_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checkout_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
