# Generated by Django 5.1.4 on 2026-05-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_checkout_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='gift',
            field=models.BooleanField(default=False),
        ),
    ]
