# Generated by Django 5.1.4 on 2026-06-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderproduct_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, choices=[('bog', 'Bank Of Georgia'), ('tbc', 'TBC Bank'), ('flitt', 'Flitt'), ('tbc_loan', 'tbc_loan'), ('liberty', 'Liberty Bank')], max_length=10, null=True),
        ),
    ]
